name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the sections below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Minimal steps or code to reproduce the behavior.
      placeholder: |
        1. Read a file with `await SymLibReader.ReadAsync("file.kicad_sym")`
        2. Access property X
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened. Include error messages or stack traces if applicable.
    validations:
      required: true

  - type: dropdown
    id: file-type
    attributes:
      label: KiCad File Type
      description: Which file type is affected?
      multiple: true
      options:
        - Symbol Library (.kicad_sym)
        - Schematic (.kicad_sch)
        - Footprint (.kicad_mod)
        - PCB Layout (.kicad_pcb)
        - Not file-type specific
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Library Version
      description: Version of OriginalCircuit.KiCad
      placeholder: "1.0.0"
    validations:
      required: true

  - type: input
    id: kicad-version
    attributes:
      label: KiCad Version
      description: Version of KiCad that produced the file (if applicable)
      placeholder: "8.0"
    validations:
      required: false

  - type: input
    id: dotnet-version
    attributes:
      label: .NET Version
      description: Output of `dotnet --version`
      placeholder: "10.0.100"
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or sample files.
    validations:
      required: false
